# Generated by Django 2.2.5 on 2020-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=120, verbose_name='Podaj swoje imię:')),
                ('email', models.EmailField(max_length=254, verbose_name='Podaj adres email:')),
                ('key', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Umówione wizyty',
            },
        ),
    ]
